# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["ChekersAPI/ChekersAPI.csproj", "ChekersAPI/"]
COPY ["CheckersEngine/CheckersEngine.csproj", "CheckersEngine/"]
RUN dotnet restore "ChekersAPI/ChekersAPI.csproj"

COPY . .
RUN dotnet publish "ChekersAPI/ChekersAPI.csproj" -c Release -o /app/publish

# Run
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Nothing is copied into Properties/ any more. This image used to bake a Firebase service
# account key in on purpose; the key is dead (Google disabled it as exposed) and the
# credential it replaced is generated by the platform per-deployment, so there is nothing
# left to carry.

# Non-root, and a fixed UID rather than a named user: the platform chart pins runAsUser
# itself and refuses to render a component that would run as root, so an image whose only
# non-root story is a USER line the orchestrator overrides is worth nothing. This makes
# `docker run` match what the cluster does.
USER 65532:65532

# ASP.NET's default is port 8080 in .NET 8, but stating it makes the contract with the
# chart's `port:` explicit rather than inherited from a base image's default.
ENV ASPNETCORE_HTTP_PORTS=8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "ChekersAPI.dll"]
