using Npgsql;

namespace ChekersAPI
{
    /// <summary>
    /// Everything this service keeps between restarts: a five-row leaderboard and a
    /// lifetime game counter.
    ///
    /// The connection is assembled from PG* environment variables rather than read from a
    /// connection string, because the credentials are generated by CloudNativePG and
    /// published as a Secret with one key per field. Nothing here is ever written by hand,
    /// which is the point — there is no database password to rotate, commit or leak.
    /// </summary>
    public static class Db
    {
        public const string GamesStartedCounter = "games_started";

        /// <summary>How many winners the board keeps. Application behaviour, carried over
        /// from the Firestore version, where it was also application behaviour.</summary>
        private const int LeaderboardSize = 5;

        /// <summary>Longest accepted winner name. The front end offers 15; this is the
        /// server's own bound, and it exists because Firestore had one (a document could
        /// not exceed ~1 MiB) and a bare TEXT column does not. Without it a single crafted
        /// request parks a multi-megabyte row on a five-row board and every visitor
        /// downloads it until five more people win.</summary>
        public const int MaxNameLength = 64;

        private static NpgsqlDataSource? s_dataSource;

        /// <summary>True once a connection has been established and the schema verified.</summary>
        public static bool Ready { get; private set; }

        public static string BuildConnectionString()
        {
            string Env(string key, string fallback) =>
                Environment.GetEnvironmentVariable(key) is { Length: > 0 } v ? v : fallback;

            var b = new NpgsqlConnectionStringBuilder
            {
                Host = Env("PGHOST", "localhost"),
                Port = int.TryParse(Env("PGPORT", "5432"), out int p) ? p : 5432,
                Username = Env("PGUSER", "checkers"),
                Password = Env("PGPASSWORD", ""),
                Database = Env("PGDATABASE", "checkers"),
                // The API and the database are two pods in one namespace on one node. TLS
                // between them buys nothing the NetworkPolicy does not already provide, and
                // CNPG's server certificate is signed by its own CA, so requiring
                // verification would mean shipping that CA into this image.
                SslMode = SslMode.Prefer,
                // A move request that blocks on the database is worse than one that fails:
                // the engine does not need the database at all, so a hung leaderboard must
                // not become a hung game.
                Timeout = 5,
                CommandTimeout = 5,
                MaxPoolSize = 10,
            };
            return b.ConnectionString;
        }

        /// <summary>
        /// Opens the pool, applies the schema, and verifies it is the schema this code
        /// expects. Idempotent, and safe to call again after a failure — the caller retries
        /// in the background rather than refusing to start, because the checkers engine is
        /// fully playable with no database at all and crash-looping against a Postgres that
        /// is still bootstrapping would take the game down with it.
        /// </summary>
        public static async Task InitializeAsync(ILogger logger, CancellationToken ct = default)
        {
            s_dataSource ??= NpgsqlDataSource.Create(BuildConnectionString());

            await using var conn = await s_dataSource.OpenConnectionAsync(ct);
            await using (var cmd = conn.CreateCommand())
            {
                cmd.CommandText = $@"
CREATE TABLE IF NOT EXISTS winners (
    id            BIGSERIAL PRIMARY KEY,
    name          TEXT        NOT NULL,
    game_sequence TEXT[]      NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

-- clock_timestamp(), not now(). now() is transaction_timestamp() — the moment the
-- transaction STARTED, before any of its work happened. A submission whose transaction ran
-- slower than its neighbours was therefore stamped as older than submissions that started
-- after it, which put it below them on a board it had just been accepted onto. Nothing
-- orders by this column any more either (see below), but a displayed timestamp that
-- predates the row's own work is still a lie.
ALTER TABLE winners ALTER COLUMN created_at SET DEFAULT clock_timestamp();

-- Bound the name in the database as well as in the model. The model binding is what returns
-- a clean 400; this is what makes an oversized row unrepresentable regardless of how it
-- arrives.
ALTER TABLE winners DROP CONSTRAINT IF EXISTS winners_name_length;
ALTER TABLE winners ADD CONSTRAINT winners_name_length CHECK (length(name) BETWEEN 1 AND {MaxNameLength});

-- GetPositionSequence indexes element 0 unguarded. An empty array is not producible by the
-- engine, but the column allowed one, and a single unreadable row failed the whole
-- leaderboard for everybody. COALESCE is load-bearing: array_length('{{}}', 1) is NULL, not
-- 0, and a CHECK that evaluates to NULL PASSES — so the constraint without it accepted
-- exactly the value it was written to reject.
ALTER TABLE winners DROP CONSTRAINT IF EXISTS winners_sequence_nonempty;
ALTER TABLE winners ADD CONSTRAINT winners_sequence_nonempty CHECK (COALESCE(array_length(game_sequence, 1), 0) >= 1);

-- Counters that must survive a restart. A Prometheus counter cannot answer 'how many games
-- have ever been played' — it resets with the process, and Prometheus is explicitly designed
-- to treat that as a reset rather than a loss. Anything presented as a lifetime total has to
-- live here.
CREATE TABLE IF NOT EXISTS counters (
    name  TEXT PRIMARY KEY,
    value BIGINT NOT NULL DEFAULT 0
);
";
                await cmd.ExecuteNonQueryAsync(ct);
            }

            await VerifySchemaAsync(conn, ct);

            Ready = true;
            logger.LogInformation("database ready at {Host}",
                new NpgsqlConnectionStringBuilder(BuildConnectionString()).Host);
        }

        /// <summary>
        /// CREATE TABLE IF NOT EXISTS is not a migration. Against a pre-existing `winners`
        /// of a different shape it succeeds silently, and the service then reports itself
        /// healthy while every write fails and the leaderboard reads as legitimately empty —
        /// a 200 with wrong data, which is the worst answer available. Confirm the columns
        /// are the ones this code writes before claiming to be ready.
        /// </summary>
        private static async Task VerifySchemaAsync(NpgsqlConnection conn, CancellationToken ct)
        {
            var expected = new Dictionary<string, (string Table, string Type)>
            {
                ["winners.id"] = ("winners", "bigint"),
                ["winners.name"] = ("winners", "text"),
                ["winners.game_sequence"] = ("winners", "ARRAY"),
                ["winners.created_at"] = ("winners", "timestamp with time zone"),
                ["counters.name"] = ("counters", "text"),
                ["counters.value"] = ("counters", "bigint"),
            };

            var found = new Dictionary<string, string>();
            await using (var cmd = conn.CreateCommand())
            {
                cmd.CommandText = @"
SELECT table_name, column_name, data_type
  FROM information_schema.columns
 WHERE table_schema = current_schema() AND table_name IN ('winners','counters')";
                await using var reader = await cmd.ExecuteReaderAsync(ct);
                while (await reader.ReadAsync(ct))
                {
                    found[$"{reader.GetString(0)}.{reader.GetString(1)}"] = reader.GetString(2);
                }
            }

            var wrong = expected
                .Where(e => !found.TryGetValue(e.Key, out string? t) || t != e.Value.Type)
                .Select(e => $"{e.Key} expected {e.Value.Type}, found {(found.TryGetValue(e.Key, out string? t) ? t : "nothing")}")
                .ToList();

            if (wrong.Count > 0)
            {
                throw new InvalidOperationException(
                    "the database schema is not the one this build expects: " + string.Join("; ", wrong));
            }
        }

        private static NpgsqlDataSource Source =>
            s_dataSource ?? throw new InvalidOperationException("database not initialised");

        /// <summary>
        /// True for failures that mean the database is unreachable, as opposed to failures
        /// that mean the request was bad.
        ///
        /// Conflating the two was exploitable: one submission with a NUL byte in the name
        /// raised a PostgresException 22021, which marked the database down and made
        /// SessionController stop recording games entirely until the next background probe.
        /// Repeating that request every twenty-five seconds suppressed the durable counter
        /// indefinitely while Postgres was perfectly healthy — and checkers_database_up, the
        /// one gauge a dashboard is meant to trust, read 0 throughout.
        /// </summary>
        private static bool IsOutage(Exception ex) => ex switch
        {
            // 08 connection, 53 insufficient resources, 57 operator intervention,
            // 58 system error. Everything else — 22 data, 23 integrity — is the caller's.
            PostgresException pg => pg.SqlState.StartsWith("08") || pg.SqlState.StartsWith("53")
                                 || pg.SqlState.StartsWith("57") || pg.SqlState.StartsWith("58"),
            NpgsqlException => true,          // socket, pool exhaustion, handshake
            TimeoutException => true,
            InvalidOperationException => true, // pool never opened, or schema mismatch
            _ => false,
        };

        private static async Task<T> Guarded<T>(Func<Task<T>> query)
        {
            try
            {
                return await query();
            }
            catch (Exception ex) when (IsOutage(ex))
            {
                Ready = false;
                GameMetrics.DatabaseUp.Set(0);
                throw;
            }
        }

        /// <summary>
        /// Adds a winner and trims the board back to the newest five.
        ///
        /// The advisory lock is the correctness of this method, not a precaution. Without it,
        /// under READ COMMITTED, two concurrent transactions cannot see each other's insert,
        /// so both compute the same "newest five", both delete the same single oldest row,
        /// and both survive: two simultaneous wins left SIX rows on a five-row board, in 25
        /// trials out of 25, and sustained concurrency held a steady state of fourteen. The
        /// previous comment here claimed this rewrite fixed exactly that. It did not — it
        /// reproduced it.
        ///
        /// Ordering is by id, never by a timestamp. With the lock held, insert order is
        /// commit order is id order. Ordering by created_at additionally let a submission
        /// trim ITSELF away and still return "added successfully", because the default was
        /// transaction-start time and a slower transaction ranked older than ones that began
        /// after it.
        /// </summary>
        public static Task AddWinnerAsync(string name, string[] gameSequence, CancellationToken ct = default) =>
            Guarded(async () => { await addWinnerAsync(name, gameSequence, ct); return true; });

        private static async Task addWinnerAsync(string name, string[] gameSequence, CancellationToken ct)
        {
            await using var conn = await Source.OpenConnectionAsync(ct);
            await using var tx = await conn.BeginTransactionAsync(ct);

            await using (var mutex = conn.CreateCommand())
            {
                // Transaction-scoped: released by commit or rollback, so a crash between the
                // insert and the trim cannot leave the board locked.
                mutex.CommandText = "SELECT pg_advisory_xact_lock(hashtext('winners_trim'))";
                await mutex.ExecuteNonQueryAsync(ct);
            }

            await using (var insert = conn.CreateCommand())
            {
                insert.CommandText = "INSERT INTO winners (name, game_sequence) VALUES (@n, @g)";
                insert.Parameters.AddWithValue("n", name);
                insert.Parameters.AddWithValue("g", gameSequence);
                await insert.ExecuteNonQueryAsync(ct);
            }

            await using (var trim = conn.CreateCommand())
            {
                trim.CommandText =
                    $"DELETE FROM winners WHERE id NOT IN (SELECT id FROM winners ORDER BY id DESC LIMIT {LeaderboardSize})";
                await trim.ExecuteNonQueryAsync(ct);
            }

            await tx.CommitAsync(ct);
        }

        public static Task<List<(string Name, string[] GameSequence)>> GetWinnersAsync(CancellationToken ct = default) =>
            Guarded(() => getWinnersAsync(ct));

        private static async Task<List<(string Name, string[] GameSequence)>> getWinnersAsync(CancellationToken ct)
        {
            var result = new List<(string, string[])>();
            await using var conn = await Source.OpenConnectionAsync(ct);
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = $"SELECT name, game_sequence FROM winners ORDER BY id DESC LIMIT {LeaderboardSize}";
            await using var reader = await cmd.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                result.Add((reader.GetString(0), reader.GetFieldValue<string[]>(1)));
            }
            return result;
        }

        public static Task<long> IncrementCounterAsync(string counter, CancellationToken ct = default) =>
            Guarded(() => incrementCounterAsync(counter, ct));

        private static async Task<long> incrementCounterAsync(string counter, CancellationToken ct)
        {
            await using var conn = await Source.OpenConnectionAsync(ct);
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = @"
INSERT INTO counters (name, value) VALUES (@n, 1)
ON CONFLICT (name) DO UPDATE SET value = counters.value + 1
RETURNING value";
            cmd.Parameters.AddWithValue("n", counter);
            return (long)(await cmd.ExecuteScalarAsync(ct))!;
        }

        public static Task<long> ReadCounterAsync(string counter, CancellationToken ct = default) =>
            Guarded(() => readCounterAsync(counter, ct));

        private static async Task<long> readCounterAsync(string counter, CancellationToken ct)
        {
            await using var conn = await Source.OpenConnectionAsync(ct);
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = "SELECT COALESCE((SELECT value FROM counters WHERE name = @n), 0)";
            cmd.Parameters.AddWithValue("n", counter);
            return (long)(await cmd.ExecuteScalarAsync(ct))!;
        }
    }
}
