using Npgsql;

namespace ChekersAPI
{
    /// <summary>
    /// Everything this service keeps between restarts: a five-row leaderboard and a
    /// lifetime game counter.
    ///
    /// The connection is assembled from PG* environment variables rather than read from a
    /// connection string, because the credentials are generated by CloudNativePG and
    /// published as a Secret with one key per field. Nothing here is ever written by hand,
    /// which is the point — there is no database password to rotate, commit or leak.
    /// </summary>
    public static class Db
    {
        public const string GamesStartedCounter = "games_started";

        private static NpgsqlDataSource? s_dataSource;

        /// <summary>True once a connection has been established and the schema applied.</summary>
        public static bool Ready { get; private set; }

        public static string BuildConnectionString()
        {
            string Env(string key, string fallback) =>
                Environment.GetEnvironmentVariable(key) is { Length: > 0 } v ? v : fallback;

            var b = new NpgsqlConnectionStringBuilder
            {
                Host = Env("PGHOST", "localhost"),
                Port = int.TryParse(Env("PGPORT", "5432"), out int p) ? p : 5432,
                Username = Env("PGUSER", "checkers"),
                Password = Env("PGPASSWORD", ""),
                Database = Env("PGDATABASE", "checkers"),
                // The API and the database are two pods in one namespace on one node.
                // TLS between them buys nothing that the NetworkPolicy does not already
                // provide, and CNPG's server certificate is signed by its own CA, so
                // requiring verification here would mean shipping that CA into this image.
                SslMode = SslMode.Prefer,
                // A move request that blocks on the database is worse than one that fails:
                // the engine does not need the database at all, so a hung leaderboard must
                // not become a hung game.
                Timeout = 5,
                CommandTimeout = 5,
                MaxPoolSize = 10,
            };
            return b.ConnectionString;
        }

        /// <summary>
        /// Opens the pool and applies the schema. Idempotent, and safe to call again after
        /// a failure — the caller retries in the background rather than refusing to start,
        /// because the checkers engine is fully playable with no database at all and
        /// crash-looping on a database that is still bootstrapping would take the game
        /// down with it.
        /// </summary>
        public static async Task InitializeAsync(ILogger logger, CancellationToken ct = default)
        {
            s_dataSource ??= NpgsqlDataSource.Create(BuildConnectionString());

            await using var conn = await s_dataSource.OpenConnectionAsync(ct);
            await using (var cmd = conn.CreateCommand())
            {
                cmd.CommandText = @"
CREATE TABLE IF NOT EXISTS winners (
    id            BIGSERIAL PRIMARY KEY,
    name          TEXT        NOT NULL,
    game_sequence TEXT[]      NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- The leaderboard is read as 'the five most recent', so that ordering is the only index
-- that earns its keep.
CREATE INDEX IF NOT EXISTS winners_created_at_desc ON winners (created_at DESC, id DESC);

-- Counters that must survive a restart. A Prometheus counter cannot answer 'how many
-- games have ever been played' — it resets with the process, and Prometheus is explicitly
-- designed to treat that as a reset rather than a loss. Anything presented as a lifetime
-- total has to live here.
CREATE TABLE IF NOT EXISTS counters (
    name  TEXT PRIMARY KEY,
    value BIGINT NOT NULL DEFAULT 0
);
";
                await cmd.ExecuteNonQueryAsync(ct);
            }

            Ready = true;
            logger.LogInformation("database ready at {Host}", new NpgsqlConnectionStringBuilder(BuildConnectionString()).Host);
        }

        private static NpgsqlDataSource Source =>
            s_dataSource ?? throw new InvalidOperationException("database not initialised");

        /// <summary>
        /// Runs a query and, if it fails, records that the database is down before letting
        /// the exception through.
        ///
        /// The background probe alone is not enough. It runs every thirty seconds, so an
        /// outage shorter than that is invisible to it: checkers_database_up read 1 for the
        /// entire duration of a real outage during which getwinners was returning 500. A
        /// health gauge that misses outages is worse than no gauge, because it is the thing
        /// a dashboard is trusted to show. Clearing Ready also makes the probe re-run its
        /// bootstrap on the next tick rather than assuming the pool is still good.
        /// </summary>
        private static async Task<T> Guarded<T>(Func<Task<T>> query)
        {
            try
            {
                return await query();
            }
            catch
            {
                Ready = false;
                GameMetrics.DatabaseUp.Set(0);
                throw;
            }
        }

        /// <summary>
        /// Adds a winner and trims the board back to the five most recent.
        ///
        /// The cap is application behaviour carried over deliberately from the Firestore
        /// version, where it was implemented as 'delete the oldest before inserting'. It is
        /// a trim after the insert here instead: the old form only removed one row per
        /// insert, so a board that ever got ahead of the cap stayed ahead of it forever,
        /// and two concurrent submissions could each delete one row and insert one, ending
        /// up at six. Doing it in one transaction as 'keep the newest five' converges from
        /// any starting state and is what the front end has always been shown.
        /// </summary>
        public static Task AddWinnerAsync(string name, string[] gameSequence, CancellationToken ct = default) =>
            Guarded(async () => { await addWinnerAsync(name, gameSequence, ct); return true; });

        private static async Task addWinnerAsync(string name, string[] gameSequence, CancellationToken ct)
        {
            await using var conn = await Source.OpenConnectionAsync(ct);
            await using var tx = await conn.BeginTransactionAsync(ct);

            await using (var insert = conn.CreateCommand())
            {
                insert.CommandText = "INSERT INTO winners (name, game_sequence) VALUES (@n, @g)";
                insert.Parameters.AddWithValue("n", name);
                insert.Parameters.AddWithValue("g", gameSequence);
                await insert.ExecuteNonQueryAsync(ct);
            }

            await using (var trim = conn.CreateCommand())
            {
                trim.CommandText = @"
DELETE FROM winners
 WHERE id NOT IN (SELECT id FROM winners ORDER BY created_at DESC, id DESC LIMIT 5)";
                await trim.ExecuteNonQueryAsync(ct);
            }

            await tx.CommitAsync(ct);
        }

        public static Task<List<(string Name, string[] GameSequence)>> GetWinnersAsync(CancellationToken ct = default) =>
            Guarded(() => getWinnersAsync(ct));

        private static async Task<List<(string Name, string[] GameSequence)>> getWinnersAsync(CancellationToken ct)
        {
            var result = new List<(string, string[])>();
            await using var conn = await Source.OpenConnectionAsync(ct);
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = "SELECT name, game_sequence FROM winners ORDER BY created_at DESC, id DESC LIMIT 5";
            await using var reader = await cmd.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                result.Add((reader.GetString(0), reader.GetFieldValue<string[]>(1)));
            }
            return result;
        }

        public static Task<long> IncrementCounterAsync(string counter, CancellationToken ct = default) =>
            Guarded(() => incrementCounterAsync(counter, ct));

        private static async Task<long> incrementCounterAsync(string counter, CancellationToken ct)
        {
            await using var conn = await Source.OpenConnectionAsync(ct);
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = @"
INSERT INTO counters (name, value) VALUES (@n, 1)
ON CONFLICT (name) DO UPDATE SET value = counters.value + 1
RETURNING value";
            cmd.Parameters.AddWithValue("n", counter);
            return (long)(await cmd.ExecuteScalarAsync(ct))!;
        }

        public static Task<long> ReadCounterAsync(string counter, CancellationToken ct = default) =>
            Guarded(() => readCounterAsync(counter, ct));

        private static async Task<long> readCounterAsync(string counter, CancellationToken ct)
        {
            await using var conn = await Source.OpenConnectionAsync(ct);
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = "SELECT COALESCE((SELECT value FROM counters WHERE name = @n), 0)";
            cmd.Parameters.AddWithValue("n", counter);
            return (long)(await cmd.ExecuteScalarAsync(ct))!;
        }
    }
}
